// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/metrics.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/metrics.go -destination=internal/service/mock/service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/kerpe-l/metrics-alerting-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockMetricsService) GetAll() (map[string]float64, map[string]int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(map[string]int64)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMetricsServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMetricsService)(nil).GetAll))
}

// GetJSON mocks base method.
func (m *MockMetricsService) GetJSON(metric model.Metrics) (model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", metric)
	ret0, _ := ret[0].(model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockMetricsServiceMockRecorder) GetJSON(metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockMetricsService)(nil).GetJSON), metric)
}

// GetValue mocks base method.
func (m *MockMetricsService) GetValue(name, mType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", name, mType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockMetricsServiceMockRecorder) GetValue(name, mType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockMetricsService)(nil).GetValue), name, mType)
}

// Update mocks base method.
func (m *MockMetricsService) Update(name, mType string, value float64, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", name, mType, value, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricsServiceMockRecorder) Update(name, mType, value, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricsService)(nil).Update), name, mType, value, delta)
}

// UpdateBatch mocks base method.
func (m *MockMetricsService) UpdateBatch(ctx context.Context, metrics []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBatch indicates an expected call of UpdateBatch.
func (mr *MockMetricsServiceMockRecorder) UpdateBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatch", reflect.TypeOf((*MockMetricsService)(nil).UpdateBatch), ctx, metrics)
}

// UpdateJSON mocks base method.
func (m *MockMetricsService) UpdateJSON(metric model.Metrics) (model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJSON", metric)
	ret0, _ := ret[0].(model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJSON indicates an expected call of UpdateJSON.
func (mr *MockMetricsServiceMockRecorder) UpdateJSON(metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJSON", reflect.TypeOf((*MockMetricsService)(nil).UpdateJSON), metric)
}
