package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func mustCheck(t *testing.T, src string) *types.Package {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "x.go", src, parser.ParseComments)
	require.NoError(t, err)
	conf := types.Config{}
	pkg, err := conf.Check("x", fset, []*ast.File{file}, nil)
	require.NoError(t, err)
	return pkg
}

func lookupStruct(t *testing.T, pkg *types.Package, name string) (*types.Named, *types.Struct) {
	t.Helper()
	named, ok := pkg.Scope().Lookup(name).Type().(*types.Named)
	require.True(t, ok, "type %s not found or not named", name)
	st, ok := named.Underlying().(*types.Struct)
	require.True(t, ok, "type %s is not a struct", name)
	return named, st
}

func lookupField(t *testing.T, st *types.Struct, name string) *types.Var {
	t.Helper()
	for i := 0; i < st.NumFields(); i++ {
		if st.Field(i).Name() == name {
			return st.Field(i)
		}
	}
	t.Fatalf("field %s not found", name)
	return nil
}

func TestEmitField(t *testing.T) {
	src := `package x

type Other struct{}

func (o *Other) Reset() {}

type NoReset struct {
	X int
	Y string
}

type S struct {
	I     int
	F     float64
	B     bool
	Str   string
	Sl    []int
	Mp    map[string]int
	PStr  *string
	POth  *Other
	Oth   Other
	NR    NoReset
	PNR   *NoReset
	Iface interface{ Foo() }
	Ch    chan int
}
`
	pkg := mustCheck(t, src)
	_, st := lookupStruct(t, pkg, "S")

	cases := []struct {
		field string
		want  string
	}{
		{"I", "\ts.I = 0\n"},
		{"F", "\ts.F = 0\n"},
		{"B", "\ts.B = false\n"},
		{"Str", "\ts.Str = \"\"\n"},
		{"Sl", "\ts.Sl = s.Sl[:0]\n"},
		{"Mp", "\tclear(s.Mp)\n"},
		{"PStr", "\tif s.PStr != nil {\n\t\t(*s.PStr) = \"\"\n\t}\n"},
		{"POth", "\tif s.POth != nil {\n\t\ts.POth.Reset()\n\t}\n"},
		{"Oth", "\ts.Oth.Reset()\n"},
		{"NR", "\ts.NR.X = 0\n\ts.NR.Y = \"\"\n"},
		{"PNR", "\tif s.PNR != nil {\n\t\t(*s.PNR).X = 0\n\t\t(*s.PNR).Y = \"\"\n\t}\n"},
		{"Iface", "\tif r, ok := s.Iface.(interface{ Reset() }); ok {\n\t\tr.Reset()\n\t}\n"},
		{"Ch", ""},
	}

	for _, tc := range cases {
		t.Run(tc.field, func(t *testing.T) {
			f := lookupField(t, st, tc.field)
			var buf strings.Builder
			emitField(&buf, "s."+f.Name(), f.Type(), nil, "\t")
			require.Equal(t, tc.want, buf.String())
		})
	}
}

func TestEmitField_WillHaveReset(t *testing.T) {
	src := `package x

type Future struct{}

type S struct {
	V Future
	P *Future
}
`
	pkg := mustCheck(t, src)
	_, st := lookupStruct(t, pkg, "S")
	future, _ := lookupStruct(t, pkg, "Future")
	willHave := map[string]bool{qualName(future): true}

	cases := []struct {
		field string
		want  string
	}{
		{"V", "\ts.V.Reset()\n"},
		{"P", "\tif s.P != nil {\n\t\ts.P.Reset()\n\t}\n"},
	}
	for _, tc := range cases {
		t.Run(tc.field, func(t *testing.T) {
			f := lookupField(t, st, tc.field)
			var buf strings.Builder
			emitField(&buf, "s."+f.Name(), f.Type(), willHave, "\t")
			require.Equal(t, tc.want, buf.String())
		})
	}
}

func TestRenderPackage(t *testing.T) {
	src := `package x

type S struct {
	I int
	S string
	M map[string]int
}
`
	pkg := mustCheck(t, src)
	named, st := lookupStruct(t, pkg, "S")

	out, err := renderPackage("x", []target{{Name: "S", Named: named, St: st}}, nil)
	require.NoError(t, err)

	want := `// Code generated by cmd/reset; DO NOT EDIT.

package x

// Reset сбрасывает поля S к нулевым значениям.
func (s *S) Reset() {
	if s == nil {
		return
	}
	s.I = 0
	s.S = ""
	clear(s.M)
}
`
	require.Equal(t, want, string(out))
}

func TestCommentHasMarker(t *testing.T) {
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"nil", "", false},
		{"unrelated", "обычный комментарий", false},
		{"exact", "generate:reset", true},
		{"with leading space", " generate:reset", true},
		{"with trailing space", "generate:reset ", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var cg *ast.CommentGroup
			if tc.body != "" {
				cg = &ast.CommentGroup{List: []*ast.Comment{{Text: "//" + tc.body}}}
			}
			require.Equal(t, tc.want, commentHasMarker(cg))
		})
	}
}

func TestRun_EndToEnd(t *testing.T) {
	tmp := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(tmp, "go.mod"),
		[]byte("module example\n\ngo 1.21\n"), 0o644))

	src := `package example

// generate:reset
type Foo struct {
	N int
	M map[string]int
	B *Bar
}

// generate:reset
type Bar struct {
	S  string
	Xs []int
}

// без маркера — должен быть пропущен
type Skipped struct {
	N int
}
`
	require.NoError(t, os.WriteFile(filepath.Join(tmp, "example.go"), []byte(src), 0o644))

	cwd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() { _ = os.Chdir(cwd) })

	require.NoError(t, run("./..."))

	out, err := os.ReadFile(filepath.Join(tmp, generatedFile))
	require.NoError(t, err)
	got := string(out)

	t.Run("header", func(t *testing.T) {
		require.True(t, strings.HasPrefix(got, generatedHeader+"\n"))
	})
	t.Run("both targets present", func(t *testing.T) {
		require.Contains(t, got, "func (b *Bar) Reset()")
		require.Contains(t, got, "func (f *Foo) Reset()")
	})
	t.Run("skipped struct absent", func(t *testing.T) {
		require.NotContains(t, got, "Skipped) Reset()")
	})
	t.Run("cross-target pointer call", func(t *testing.T) {
		require.Contains(t, got, "f.B.Reset()")
	})
	t.Run("slice and map handling", func(t *testing.T) {
		require.Contains(t, got, "b.Xs = b.Xs[:0]")
		require.Contains(t, got, "clear(f.M)")
	})

	// Идемпотентность: повторный запуск даёт тот же результат и не
	// сканирует сгенерированный файл как источник новых целей.
	t.Run("idempotent", func(t *testing.T) {
		require.NoError(t, run("./..."))
		out2, err := os.ReadFile(filepath.Join(tmp, generatedFile))
		require.NoError(t, err)
		require.Equal(t, got, string(out2))
	})
}

func TestReceiverName(t *testing.T) {
	require.Equal(t, "m", receiverName("Metric"))
	require.Equal(t, "x", receiverName("xML"))
	require.Equal(t, "r", receiverName(""))
}
