package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const (
	marker          = "generate:reset"
	generatedFile   = "reset.gen.go"
	generatedHeader = "// Code generated by cmd/reset; DO NOT EDIT."
)

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Использование: %s [pattern]\n\n", filepath.Base(os.Args[0]))
		fmt.Fprintln(os.Stderr, "Сканирует пакеты Go и генерирует методы Reset()")
		fmt.Fprintln(os.Stderr, "для структур с комментарием // "+marker+".")
		flag.PrintDefaults()
	}
	flag.Parse()

	pattern := "./..."
	if flag.NArg() > 0 {
		pattern = flag.Arg(0)
	}
	if err := run(pattern); err != nil {
		log.SetFlags(0)
		log.Fatalf("reset: %v", err)
	}
}

// target — найденная цель генерации: структура с маркером // generate:reset.
type target struct {
	Name  string
	Named *types.Named
	St    *types.Struct
}

func run(pattern string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedImports | packages.NeedDeps,
	}
	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return fmt.Errorf("загрузка пакетов: %w", err)
	}
	if n := packages.PrintErrors(pkgs); n > 0 {
		return fmt.Errorf("в пакетах найдено ошибок: %d", n)
	}

	type pkgWork struct {
		pkg     *packages.Package
		targets []target
	}
	var work []pkgWork
	willHave := map[string]bool{}
	for _, p := range pkgs {
		ts := findTargets(p)
		if len(ts) == 0 {
			continue
		}
		for _, t := range ts {
			willHave[qualName(t.Named)] = true
		}
		work = append(work, pkgWork{pkg: p, targets: ts})
	}
	sort.Slice(work, func(i, j int) bool { return work[i].pkg.PkgPath < work[j].pkg.PkgPath })

	for _, w := range work {
		src, err := renderPackage(w.pkg.Name, w.targets, willHave)
		if err != nil {
			return fmt.Errorf("рендеринг %s: %w", w.pkg.PkgPath, err)
		}
		dir, err := packageDir(w.pkg)
		if err != nil {
			return fmt.Errorf("поиск каталога %s: %w", w.pkg.PkgPath, err)
		}
		out := filepath.Join(dir, generatedFile)
		if err := os.WriteFile(out, src, 0o644); err != nil {
			return fmt.Errorf("запись %s: %w", out, err)
		}
		fmt.Fprintf(os.Stderr, "reset: %s (типов: %d)\n", out, len(w.targets))
	}
	return nil
}

// findTargets возвращает все структуры пакета, помеченные маркером
// // generate:reset, в детерминированном порядке по имени.
func findTargets(p *packages.Package) []target {
	var out []target
	for _, file := range p.Syntax {
		if ast.IsGenerated(file) {
			continue
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				tspec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := tspec.Type.(*ast.StructType); !ok {
					continue
				}
				if !commentHasMarker(tspec.Doc) && !commentHasMarker(gd.Doc) {
					continue
				}
				obj, ok := p.TypesInfo.Defs[tspec.Name].(*types.TypeName)
				if !ok {
					continue
				}
				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}
				st, ok := named.Underlying().(*types.Struct)
				if !ok {
					continue
				}
				out = append(out, target{Name: tspec.Name.Name, Named: named, St: st})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// commentHasMarker сообщает, содержит ли группа комментариев строку
// `// generate:reset` (без учёта пробелов вокруг).
func commentHasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == marker {
			return true
		}
	}
	return false
}

func packageDir(p *packages.Package) (string, error) {
	if len(p.GoFiles) == 0 {
		return "", fmt.Errorf("пакет %s не содержит Go-файлов", p.PkgPath)
	}
	return filepath.Dir(p.GoFiles[0]), nil
}

// renderPackage возвращает отформатированный исходник reset.gen.go
// для пакета с заданным именем и набором целей. willHave содержит
// квалифицированные имена типов, у которых Reset() появится в этом же
// прогоне (нужно для перекрёстных ссылок между целями).
func renderPackage(pkgName string, targets []target, willHave map[string]bool) ([]byte, error) {
	var body strings.Builder
	for _, t := range targets {
		recv := receiverName(t.Name)
		fmt.Fprintf(&body, "\n// Reset сбрасывает поля %s к нулевым значениям.\n", t.Name)
		fmt.Fprintf(&body, "func (%s *%s) Reset() {\n", recv, t.Name)
		fmt.Fprintf(&body, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)
		emitStruct(&body, recv, t.St, willHave, "\t")
		body.WriteString("}\n")
	}

	var src strings.Builder
	src.WriteString(generatedHeader)
	src.WriteString("\n\npackage ")
	src.WriteString(pkgName)
	src.WriteString("\n")
	src.WriteString(body.String())

	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return nil, fmt.Errorf("форматирование: %w\n--- сырой текст ---\n%s", err, src.String())
	}
	return formatted, nil
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return string(unicode.ToLower(r))
	}
	return "r"
}

// emitStruct эмитит сброс всех полей структуры с заданным префиксом
// доступа (например, "rs" для получателя или "(*rs.p)" для разыменования).
func emitStruct(buf *strings.Builder, prefix string, st *types.Struct, willHave map[string]bool, indent string) {
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		emitField(buf, prefix+"."+f.Name(), f.Type(), willHave, indent)
	}
}

// emitField эмитит сброс одного поля. access — выражение доступа к
// полю (например, "rs.field"), t — тип поля.
func emitField(buf *strings.Builder, access string, t types.Type, willHave map[string]bool, indent string) {
	switch tt := t.(type) {
	case *types.Basic:
		emitBasic(buf, access, tt, indent)

	case *types.Slice:
		fmt.Fprintf(buf, "%s%s = %s[:0]\n", indent, access, access)

	case *types.Map:
		fmt.Fprintf(buf, "%sclear(%s)\n", indent, access)

	case *types.Pointer:
		if hasOrWillHaveReset(t, willHave) {
			fmt.Fprintf(buf, "%sif %s != nil {\n", indent, access)
			fmt.Fprintf(buf, "%s\t%s.Reset()\n", indent, access)
			fmt.Fprintf(buf, "%s}\n", indent)
			return
		}
		fmt.Fprintf(buf, "%sif %s != nil {\n", indent, access)
		emitField(buf, "(*"+access+")", tt.Elem(), willHave, indent+"\t")
		fmt.Fprintf(buf, "%s}\n", indent)

	case *types.Named:
		if hasOrWillHaveReset(t, willHave) {
			fmt.Fprintf(buf, "%s%s.Reset()\n", indent, access)
			return
		}
		emitField(buf, access, tt.Underlying(), willHave, indent)

	case *types.Struct:
		emitStruct(buf, access, tt, willHave, indent)

	case *types.Interface:
		fmt.Fprintf(buf, "%sif r, ok := %s.(interface{ Reset() }); ok {\n", indent, access)
		fmt.Fprintf(buf, "%s\tr.Reset()\n", indent)
		fmt.Fprintf(buf, "%s}\n", indent)

		// *types.Array, *types.Chan, *types.Signature, *types.Tuple —
		// поведение в задании не определено, оставляем без изменений.
	}
}

func emitBasic(buf *strings.Builder, access string, b *types.Basic, indent string) {
	switch info := b.Info(); {
	case info&types.IsBoolean != 0:
		fmt.Fprintf(buf, "%s%s = false\n", indent, access)
	case info&types.IsString != 0:
		fmt.Fprintf(buf, "%s%s = \"\"\n", indent, access)
	case info&types.IsNumeric != 0:
		fmt.Fprintf(buf, "%s%s = 0\n", indent, access)
	}
}

// hasOrWillHaveReset сообщает, есть ли (или появится ли в этом запуске)
// у типа метод Reset() с нулевой сигнатурой. Учитывает методы как T,
// так и *T: поля адресуемы и Go автоматически возьмёт адрес.
func hasOrWillHaveReset(t types.Type, willHave map[string]bool) bool {
	if hasResetMethod(t) {
		return true
	}
	if _, isPtr := t.(*types.Pointer); !isPtr {
		if hasResetMethod(types.NewPointer(t)) {
			return true
		}
	}
	var named *types.Named
	switch tt := t.(type) {
	case *types.Named:
		named = tt
	case *types.Pointer:
		if n, ok := tt.Elem().(*types.Named); ok {
			named = n
		}
	}
	return named != nil && willHave[qualName(named)]
}

func hasResetMethod(t types.Type) bool {
	ms := types.NewMethodSet(t)
	for i := 0; i < ms.Len(); i++ {
		obj := ms.At(i).Obj()
		if obj.Name() != "Reset" {
			continue
		}
		sig, ok := obj.Type().(*types.Signature)
		if !ok {
			continue
		}
		if sig.Params().Len() == 0 && sig.Results().Len() == 0 {
			return true
		}
	}
	return false
}

func qualName(n *types.Named) string {
	obj := n.Obj()
	if pkg := obj.Pkg(); pkg != nil {
		return pkg.Path() + "." + obj.Name()
	}
	return obj.Name()
}
