// Code generated by cmd/reset; DO NOT EDIT.

package audit

// Reset сбрасывает поля Event к нулевым значениям.
func (e *Event) Reset() {
	if e == nil {
		return
	}
	e.Timestamp = 0
	e.Metrics = e.Metrics[:0]
	e.IPAddress = ""
}
